### ISSUE TITLE
layout

### ISSUE THREAD

**Issue by mrgomdev** [gichani/BasicAlgorithm1#1]
https://github.com/gichani/BasicAlgorithm1/blob/408bdfc10cc477a879350d02a4c597497a079a0c/3for/layout/layout.py#L23
https://github.com/gichani/BasicAlgorithm1/blob/408bdfc10cc477a879350d02a4c597497a079a0c/3for/layout/layout.py#L31
왜 같은 뜻의 구문을, if와 else 양쪽 모두에 썼고, 표현도 다르게 했나요?

**Comment by simpleboss** [comment]
코드를 몇일에 걸쳐서 수정하다보니, 중복이 됐네요
